### ISSUE TITLE
swarm-listener is no longer responding on port 8080

### ISSUE THREAD

**Issue by gudmojo** [docker-flow/docker-flow-swarm-listener#14]
**Description**

After weeks of running healthy, now after redeployment it seems that swarm-listener is no longer responding on port 8080. This may be a configuration error on my part, but I'm not able to figure it out, and the logs of swarm-listener are not indicating anything helpful.

**Steps to reproduce the issue:**
1. start image `vfarcic/docker-flow-swarm-listener:18.04.02-1` as a swarm service, connected to a docker overlay network called monitor2:
```
  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener:18.04.02-1
    networks:
      - monitor2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_INCLUDE_NODE_IP_INFO=true
      - DF_NOTIFY_CREATE_SERVICE_URL=http://monitor:8080/v1/docker-flow-monitor/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://monitor:8080/v1/docker-flow-monitor/remove
      - DF_NOTIFY_CREATE_NODE_URL=http://monitor:8080/v1/docker-flow-monitor/node/reconfigure
      - DF_NOTIFY_REMOVE_NODE_URL=http://monitor:8080/v1/docker-flow-monitor/node/remove
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - com.df.scrapeNetwork=monitor2
```
2. Execute `docker run --rm --network monitor2 appropriate/curl -L http://swarm-listener:8080/v1/docker-flow-swarm-listener/notify-services`

**Describe the results you received:**

> curl: (7) Failed to connect to swarm-listener port 8080: Connection refused

**Describe the results you expected:**
a successful curl invocation

**Additional information you deem important (e.g. issue happens only occasionally):**
Here are the logs from swarm-listener:

```
14:33:11 Starting Docker Flow: Swarm Listener
14:33:11 Sending notifications for running services and nodes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

baremetal machines. Docker version 17.06.0-ce, build 02c1d87

Updating to vfarcic/docker-flow-swarm-listener:18.04.12-7 did not resolve the issue.
