### ISSUE TITLE
CURL /v1/docker-flow-swarm-listener/get-nodes return 404

### ISSUE THREAD

**Issue by jaschaio** [docker-flow/docker-flow-swarm-listener#3]
I have set up docker swarm listener like this:

```
    swarm-listener:
        image: dockerflow/docker-flow-swarm-listener:18.04.15-5
        networks:
            - proxy
            - monitor
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - DF_NOTIFY_CREATE_SERVICE_URL=http://letsencrypt:8080/v1/docker-flow-proxy-letsencrypt/reconfigure,http://monitor:8080/v1/docker-flow-monitor/reconfigure
            - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove,http://monitor:8080/v1/docker-flow-monitor/remove
            - DF_NOTIFY_CREATE_NODE_URL=http://monitor:8080/v1/docker-flow-monitor/node/reconfigure
            - DF_NOTIFY_REMOVE_NODE_URL=http://monitor:8080/v1/docker-flow-monitor/node/remove
            - DF_INCLUDE_NODE_IP_INFO=true
            - DF_RETRY_INTERVAL=5
        deploy:
            placement:
                constraints:
                    - node.role == manager
```

If I deploy it like this the health check seems to fail each time (`task: non-zero exit (2): dockerexec: unhealthy container`) and restarts another container.

If I try to `curl` the `/v1/docker-flow-swarm-listener/get-nodes` I get a 404 not found error.

Curling any other endpoint (for example `/v1/docker-flow-swarm-listener/get-services`) does work as expected.

I actually noticed that problem as I only get the internal service IPs within my `docker-flow-monitor` prometheus exporters.

If I remove the `DF_NOTIFY_CREATE_NODE_URL`, `DF_NOTIFY_REMOVE_NODE_URL` and `DF_INCLUDE_NODE_IP_INFO` the service works without problems. If I include any of them the healthcheck fails.
