### ISSUE TITLE
Notification if container is unealthy > renew

### ISSUE THREAD

**Issue by nlevee** [docker-flow/docker-flow-swarm-listener#40]
Is the listener is capable of sending notification if a container in a service is unhealthy then renew ?

Thanks

**Comment by nlevee** [comment]
This is not what happen with version 18.11.28-19 : when my service is unhealthy, docker swarm kill the container and restart another one. But the listener don't send any notification.

Do you need more information ?

**Comment by thomasjpfan** [comment]
Can you provide information about how your service is set up?

**Comment by nlevee** [comment]
my services are set up like this : 

```
version: '3.4'

services:
  webapp-front-http:
    image: apache:latest
    ports:
        - "80"
    healthcheck: 
      test: "curl -f http://127.0.0.1/server-status?auto || exit 1"
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      mode: replicated
      replicas: 3
      labels:
        com.df.consulName: 'front-http'
        com.df.stackName: 'regiecamp_webapp'
        com.df.scrapeNetwork: 'regiecamp_webapp_default'
        com.df.notify: 'true'
        com.df.port: '80'
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
        parallelism: 3
```
