### ISSUE TITLE
Can't get proxy to work with subdomains - 503 errors

### ISSUE THREAD

**Issue by green3g** [docker-flow/docker-flow-swarm-listener#42]
**Description**

I'm trying to get proxy to work with the labels `com.df.hostname: pihole.local` but proxy always returns 503 errors. 
![image](https://user-images.githubusercontent.com/5471079/77856916-1056b980-71c0-11ea-88d9-e8cec1531e01.png)

**Steps to reproduce the issue:**
I'm using this with pihole, for example:
```yml
version: '3.3'
services:
  pihole:
    image: pihole/pihole:latest
    extra_hosts:
     - pihole.local:192.168.1.100
     - proxy.local:192.168.1.100
    environment:
      ServerIP: 192.168.1.100
      TZ: America/Chicago
      VIRTUAL_HOST: pihole.local
      VIRTUAL_PORT: '80'
      WEBPASSWORD: password
    ports:
     - '53:53'
     - 53:53/udp
     - 67:67/udp
     - 580:80
     - 5443:443
    volumes:
     - etc:/etc/pihole/
     - dnsmasq:/etc/dnsmasq.d/
    networks:
     - proxy
    logging:
      driver: json-file
    deploy:
      labels:
        com.df.hostname: pihole.local
        com.df.notify: 'true'
        com.df.port: '580'
        com.df.servicePath: /
        com.df.servicePort: '580'
networks:
  proxy:
    external: true
volumes:
  dnsmasq:
    driver: local
  etc:
    driver: local
```

proxy stack compose file:
```yml
version: '3.3'
services:
  proxy:
    image: dockerflow/docker-flow-proxy:latest
    environment:
      DEBUG: 'true'
      LISTENER_ADDRESS: swarm-listener
      MODE: swarm
    ports:
     - 80:80
     - 81:8080
     - 443:443
    networks:
     - proxy
    logging:
      driver: json-file
    deploy:
      replicas: 2
  swarm-listener:
    image: dockerflow/docker-flow-swarm-listener:latest
    environment:
      DEBUG: 'true'
      DF_NOTIFY_CREATE_SERVICE_URL: http://proxy:81/v1/docker-flow-proxy/reconfigure
      DF_NOTIFY_REMOVE_SERVICE_URL: http://proxy:81/v1/docker-flow-proxy/remove
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
     - proxy
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
         - node.role == manager
networks:
  proxy:
    external: true
```

**Additional information you deem important (e.g. issue happens only occasionally):**
- I'm using docker swarm - and deploying this with swarmpit
- I've created an external overlay network "proxy"

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running the swarm on Raspbian Buster - raspberry pi's. 

Errors are being logged by the proxy listener:
```
vkpeb  2020/03/29 17:59:29 Retrying service created notification to http://proxy:81/v1/docker-flow-proxy/reconfigure?distribute=true&hostname=pihole.local&port=580&replicas=1&serviceName=pihole_pihole&servicePath=%2F&servicePort=580 (46 try)
vkpeb  2020/03/29 17:59:34 Retrying service created notification to http://proxy:81/v1/docker-flow-proxy/reconfigure?distribute=true&hostname=pihole.local&port=580&replicas=1&serviceName=pihole_pihole&servicePath=%2F&servicePort=580 (47 try)
vkpeb  2020/03/29 17:59:39 Retrying service created notification to http://proxy:81/v1/docker-flow-proxy/reconfigure?distribute=true&hostname=pihole.local&port=580&replicas=1&serviceName=pihole_pihole&servicePath=%2F&servicePort=580 (48 try)
vkpeb  2020/03/29 17:59:44 Retrying service created notification to http://proxy:81/v1/docker-flow-proxy/reconfigure?distribute=true&hostname=pihole.local&port=580&replicas=1&serviceName=pihole_pihole&servicePath=%2F&servicePort=580 (49 try)
vkpeb  2020/03/29 17:59:49 Retrying service created notification to http://proxy:81/v1/docker-flow-proxy/reconfigure?distribute=true&hostname=pihole.local&port=580&replicas=1&serviceName=pihole_pihole&servicePath=%2F&servicePort=580 (50 try)
vkpeb  2020/03/29 17:59:54 ERROR: Get http://proxy:81/v1/docker-flow-proxy/reconfigure?distribute=true&hostname=pihole.local&port=580&replicas=1&serviceName=pihole_pihole&servicePath=%2F&servicePort=580: dial tcp 10.0.2.5:81: connect: connection refused
vkpeb  2020/03/29 17:59:54 ERROR: Unable to send ServiceCreateNotify to http://proxy:81/v1/docker-flow-proxy/reconfigure, params: distribute=true&hostname=pihole.local&port=580&replicas=1&serviceName=pihole_pihole&servicePath=%2F&servicePort=580
```

Update: 

I can manually run the update through the browser - this results in the proxy server logging the following:
```
ujrn3  2020/03/29 21:59:38 Creating configuration for the service pihole_pihole
ujrn3  2020/03/29 21:59:38 Reloading the proxy
ujrn3  2020/03/29 21:59:38 Validating configuration
ujrn3  Configuration file is valid
ujrn3  2020/03/29 21:59:38 HAPRoxy: Proxy services started.
ujrn3  2020/03/29 21:59:38 HAPRoxy: Proxy pihole_pihole-be580_0 started.
ujrn3  2020/03/29 21:59:38 HAPRoxy: Stopping frontend services in 0 ms.
ujrn3  2020/03/29 21:59:38 HAPRoxy: Stopping backend pihole_pihole-be580_0 in 0 ms.
ujrn3  2020/03/29 21:59:38 HAPRoxy: Proxy services stopped (FE: 2 conns, BE: 0 conns).
ujrn3  2020/03/29 21:59:38 HAPRoxy: Proxy pihole_pihole-be580_0 stopped (FE: 0 conns, BE: 2 conns).
ujrn3  2020/03/29 21:59:39 Proxy config was reloaded
xuhgr  2020/03/29 22:00:14 HAPRoxy: 10.0.0.2:50326 [29/Mar/2020:22:00:11.221] services pihole_pihole-be580_0/pihole_pihole 0/3009/-1/-1/3011 503 687 - - SC-- 1/1/0/0/3 0/0 "GET / HTTP/1.1"
ujrn3  2020/03/29 22:00:17 HAPRoxy: 10.0.0.2:50330 [29/Mar/2020:22:00:14.276] services pihole_pihole-be580_0/pihole_pihole 0/3008/-1/-1/3008 503 687 - - SC-- 1/1/0/0/3 0/0 "GET /favicon.ico HTTP/1.1"
xuhgr  2020/03/29 22:05:02 HAPRoxy: 10.0.0.2:50362 [29/Mar/2020:22:04:59.528] services pihole_pihole-be580_0/pihole_pihole 0/3010/-1/-1/3011 503 687 - - SC-- 1/1/0/0/3 0/0 "GET / HTTP/1.1"
ujrn3  2020/03/29 22:05:05 HAPRoxy: 10.0.0.2:50374 [29/Mar/2020:22:05:02.675] services pihole_pihole-be580_0/pihole_pihole 0/3008/-1/-1/3009 503 687 - - SC-- 1/1/0/0/3 0/0 "GET /favicon.ico HTTP/1.1"
xuhgr  2020/03/29 22:06:00 HAPRoxy: 10.0.0.2:50386 [29/Mar/2020:22:05:57.019] services pihole_pihole-be580_0/pihole_pihole 0/3011/-1/-1/3013 503 687 - - SC-- 1/1/0/0/3 0/0 "GET / HTTP/1.1"
ujrn3  2020/03/29 22:06:03 HAPRoxy: 10.0.0.2:50396 [29/Mar/2020:22:06:00.157] services pihole_pihole-be580_0/pihole_pihole 0/3008/-1/-1/3009 503 687 - - SC-- 1/1/0/0/3 0/0 "GET /favicon.ico HTTP/1.1"
```

I can see the following haproxy.cfg file generated:
```
# cat haproxy.cfg
global
    pidfile /var/run/haproxy.pid
    stats socket /var/run/haproxy.sock mode 660 level admin expose-fd listeners
    tune.ssl.default-dh-param 2048
    log 127.0.0.1:1514 local0

    # disable sslv3, prefer modern ciphers
    ssl-default-bind-options no-sslv3
    ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS

    ssl-default-server-options no-sslv3
    ssl-default-server-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS

resolvers docker
    nameserver dns 127.0.0.11:53

defaults
    mode    http
    balance roundrobin

    option  http-keep-alive
    option  redispatch

    errorfile 400 /errorfiles/400.http
    errorfile 403 /errorfiles/403.http
    errorfile 405 /errorfiles/405.http
    errorfile 408 /errorfiles/408.http
    errorfile 429 /errorfiles/429.http
    errorfile 500 /errorfiles/500.http
    errorfile 502 /errorfiles/502.http
    errorfile 503 /errorfiles/503.http
    errorfile 504 /errorfiles/504.http

    maxconn 5000
    timeout connect 5s
    timeout client  20s
    timeout server  20s
    timeout queue   30s
    timeout tunnel  3600s
    timeout http-request 5s
    timeout http-keep-alive 15s


frontend services
    bind *:80
    bind *:443
    mode http
    option  forwardfor

    option httplog
    log global
    acl url_pihole_pihole580_0 path_beg /
    acl domain_pihole_pihole580_0 hdr_beg(host) -i pihole.local
    use_backend pihole_pihole-be580_0 if url_pihole_pihole580_0 domain_pihole_pihole580_0





backend pihole_pihole-be580_0
    mode http
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    log global
    server pihole_pihole pihole_pihole:580
```
