### ISSUE TITLE
swarm-listener doesn't receive updates as services are created or removed

### ISSUE THREAD

**Issue by ambrons** [docker-flow/docker-flow-swarm-listener#5]
**Description**
DF swarm listener recently started not updating when we deploy or remove our stack file from the swarm.  We've had to manually force update swarm listener or scale it to 0 and back 1 again to pick up changes.  The later still works without issue, but isn't ideal.

We are using Docker4AWS and have been using DockerFlow Proxy and Swarm listener since 17.03.  We first started seeing this issue when we upgraded our D4AWS to 18.03.  W've also deployed a new swarm with 18.05 and are still seeing the same behavior with DF Swarm Listener.

I believe the issue is with Swarm Listener and not the proxy because I'm not seeing log messages from the Swarm Listener about sending out rest calls to proxies when services are added and removed like we normally do.

**Steps to reproduce the issue:**
1.  Setup D4AWS 18.03+
2. Create stack file that includes DF Swarm Listener and Proxy
3. Create another stack file that includes a service using labels for Swarm Listener and Proxy
4. Create shared network `docker -H localhost:2374 network create -d overlay proxy`
5. Remote deploy using technique from your DevOps Book to connect to remote swarm
```
docker -H localhost:2374 stack deploy -c <step-2-stack-file> --with-registry-auth proxy
```
6. Remote deploy using technique from your DevOps Book to connect to remote swarm 
```
docker -H localhost:2374 stack deploy -c <step-3-stack-file> --with-registry-auth my-stack
```

**DF Stack File**
```
version: '3.1'

services:

  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - TIMEOUT_SERVER=60
      - CONNECTION_MODE=http-server-close
    secrets:
      - source: cert.pem
        target: cert.pem
        mode: 292
    deploy:
      replicas: 2

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

secrets:
  cert.pem:
    external: true

networks:
  proxy:
    external: true
```

**Example of service definition in stack file**
```
version: '3.1'
services:

  ui:
    image: node-react-service-starts-on-port-3000
    ports:
      - "3000"
    networks:
      - proxy
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 120s
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=my.domain
        - com.df.httpsOnly=true
        - com.df.servicePath=/
        - com.df.port=3000

networks:
  proxy:
    external: true
```

**Comment by davidwmartines** [comment]
I am also seeing this issue, after running `docker service rm <service>`,  I see swarm-listener is still trying to send service creation notification to  dfp for `<service>`.

Additionally, if I create another service that uses the same `serviceDomain` as a previously removed service, swarm-listener does not send notification to dfp for the new service, but continues to send notification of removed service.

**Comment by thomasjpfan** [comment]
@ambrons Using your example, the following is a simplifying example that works. Maybe you can adapt it to meet your needs:

**proxy.yml**
```yaml
version: '3.1'

services:

  proxy:
    image: dockerflow/docker-flow-proxy:18.05.08-46
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - TIMEOUT_SERVER=60
      - CONNECTION_MODE=http-server-close
    deploy:
      replicas: 2

  swarm-listener:
    image: dockerflow/docker-flow-swarm-listener:18.05.14-6
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  proxy:
    external: true
```

**nginx.yml**
```yaml
version: '3.1'
services:

  ui:
    image: nginx:1.13.12-alpine
    ports:
      - "3000:80"
    networks:
      - proxy
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 120s
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.port=80

networks:
  proxy:
    external: true
```

Then run the following:

```bash
docker network create -d overlay proxy
docker stack deploy -c proxy.yml proxy
docker stack deploy -c nginx.yml nginx
```

@davidwmartines Can you provide an example of your stack where you encounter your error?

**Comment by ambrons** [comment]
@thomasjpfan I appreciate the example.  I don't think it's an understand issue unless configuration has breaking changes recently. I've been using it for two years with updates along the way with no problem.  However recently with [Docker 4 AWS cloud formation](https://console.aws.amazon.com/cloudformation/home#/stacks/new?stackName=Docker&templateURL=https://editions-us-east-1.s3.amazonaws.com/aws/edge/Docker-no-vpc.tmpl) as of 18.03 it started getting intermittent and with more recent versions doesn't work at all except on start.

I'd point out that I'm also using https only and serviceDomain, but honestly I don't think that matters because the issue is that swarm-listener does NOTHING when a service is added or removed.  No log output, doesn't shutdown, doesn't die, nothing.  Which typically you would get messages in the log where it's pushing updates to the configured REST urls.

In your configuration did you use the latest version of Docker for AWS or just configure a local swarm using docker-machine or the like?

**Comment by thomasjpfan** [comment]
@ambrons  I did only use a `docker-machine` for my example. I will spin up a AWS cloud formation and see if I can pinpoint the error. Thanks for the additional details!

**Comment by thomasjpfan** [comment]
I am still unable to reproduce this issue on AWS using `Docker version 18.03.0-ce, build 0520e24`. Here is what I did:

1. Export commonly used variables:

```bash
export STACK_NAME=devops22
export KEY_FILE=devops22.pem # Location of pem file
export KEY_NAME=devops22
```

2. Create AWS stack with one manager for testing purposes:

```bash
aws cloudformation create-stack \
    --template-url https://editions-us-east-1.s3.amazonaws.com/aws/stable/Docker.tmpl \
    --capabilities CAPABILITY_IAM \
    --stack-name $STACK_NAME \
    --parameters \
    ParameterKey=ManagerSize,ParameterValue=1 \
    ParameterKey=ClusterSize,ParameterValue=0 \
    ParameterKey=KeyName,ParameterValue=$KEY_NAME \
    ParameterKey=EnableSystemPrune,ParameterValue=yes \
    ParameterKey=EnableCloudWatchLogs,ParameterValue=no \
    ParameterKey=EnableCloudStorEfs,ParameterValue=yes \
    ParameterKey=ManagerInstanceType,ParameterValue=t2.micro \
    ParameterKey=InstanceType,ParameterValue=t2.micro
```

3. Wait for cluster to come online:

```bash
aws cloudformation describe-stacks \
    --stack-name $STACK_NAME | \
    jq -r ".Stacks[0].StackStatus"
```

4. Get cluster ip:

```bash
CLUSTER_IP=$(aws ec2 describe-instances \
    | jq -r ".Reservations[] \
    .Instances[] \
    | select(.SecurityGroups[].GroupName \
    | contains(\"$STACK_NAME-ManagerVpcSG\"))\
    .PublicIpAddress" \
    | tail -n 1)
```

5. Log into instance:

```bash
ssh -i $KEY_FILE docker@$CLUSTER_IP
```

6. Create the `proxy.yml` and `nginx.yml` from my previous comment and run:

```bash
docker network create -d overlay proxy
docker stack deploy -c proxy.yml proxy
docker stack deploy -c nginx.yml nginx
```

7. Cycle `docker stack rm nginx` and `docker stack deploy -c nginx.yml nginx` to see if there are issues with DFSL notificatinos.

I have not found any issues with this example. Besides the certs and the serviceDomain, is there anything different from your setup and my example?

**Comment by vce-xx** [comment]
I am having the same issue as @ambrons on current Docker for AWS 18.03.0
The swarm listener isn't catching the events (not a single log line shows up besides the ones from startup).
Scaling the listener to 0 replicas and then back to 1 forces the DFP update (@ambrons nice workaround).
Exactly as if no event was coming from /var/run/docker.sock or DFSL wasn't even listening.

My DFP config :
```
version: "3.4"
services:
  my-proxy:
    image: dockerflow/docker-flow-proxy:18.05.23-50
    ports:
      - 443:443
    networks:
      - my-proxy-net
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - SERVICE_NAME=my-proxy
      - CHECK_RESOLVERS=true
      - DEFAULT_PORTS=443:ssl
      - RELOAD_INTERVAL=60000
    secrets:
      - my-cert.pem

  swarm-listener:
    image: dockerflow/docker-flow-swarm-listener:18.05.16-12
    # image: dockerflow/docker-flow-swarm-listener:18.04.15-5 same behavior with this one
    networks:
      - my-proxy-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://my-proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://my-proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  my-proxy-net:
    external: true

secrets:
  my-cert.pem:
    external: true
```
My service :
```
version: "3.2"

networks:
  my-proxy-net:
    external:
      name: my-proxy-net

services:
  portainer:
    image: portainer/portainer
    networks:
      - my-proxy-net
    command: [
        "-H", "tcp://tasks.agent:9001", "--tlsskipverify"
    ]
    deploy:
      labels:
        - "com.df.notify=true"
        - "com.df.servicePath=/"
        - "com.df.port=9000"
        - "com.df.srcPort=443"
```

In DFSL logs, nothing besides startup logs :
```
2018/05/27 14:23:20 Starting Docker Flow: Swarm Listener
2018/05/27 14:23:20 Sending notifications for running services and nodes
```
and a few lines like this for services that were already launched when starting DFSL :
```
2018/05/27 14:23:25 Sending service created notification to http://my-proxy:8080/v1/docker-flow-proxy/reconfigure?...
```
Those are nicely taken into account by DFP (thus the above mentioned workaround)

Some ideas in order to help :
Is there some debug mode we could activate on DFSL ?
Or maybe a simpler event logger from the Swarm community that I could add to my stack in order to verify that those events are actually fired by Swarm ?

**Comment by thomasjpfan** [comment]
@vce-xx I have upated DFSL to address a bug that may have caused this issue. Please try `dockerflow/docker-flow-swarm-listener:18.05.27-15` and see if it fixes your issue.

I am in the process to adding a DEBUG logging flag to DFSL to make it easier to debug issues in the future.

**Comment by thomasjpfan** [comment]
You can observe the events emitted by docker swarm by running `docker events` https://docs.docker.com/engine/reference/commandline/events/. To specify service events run `docker events --filter type=service`.

**Comment by vce-xx** [comment]
I had the same idea and launched `docker events` command  (but without the filter on services) and the result is interesting : it keeps firing a triplet of (container exec_create, container exec_start, container exec_die) events from the swarm-listener.

Even with latest 18.05.27-15 :
```
2018-05-27T19:14:29.124365816Z container exec_die d3332626cfb71b4faf11f44c990eed3e7e3f2b5d643d4e23d37bdd2582934154 (
com.docker.stack.namespace=my-proxy, com.docker.swarm.node.id=9i8857es9ngyvyb0q7zeq0ixb, 
com.docker.swarm.service.id=ubponk120fb4njkodatmjv1a9, com.docker.swarm.service.name=my-proxy_swarm-listener, 
com.docker.swarm.task=, com.docker.swarm.task.id=etz1k5rfhv74ec83d9iqut8oe, 
com.docker.swarm.task.name=my-proxy_swarm-listener.1.etz1k5rfhv74ec83d9iqut8oe, 
execID=1c581afb91c6dcfb613dce5fcc91bbfaa4a4339ab972c633c020d56cd070efe7, exitCode=0, image=dockerflow/
docker-flow-swarm-listener:18.05.27-15@sha256:50d06efdf9c2439e90dc802ab07ad96451a6835c0cc2d06bcf2c6ea2ae03b288, 
maintainer=Viktor Farcic <viktor@farcic.com>, name=my-proxy_swarm-listener.1.etz1k5rfhv74ec83d9iqut8oe)
```

**Comment by thomasjpfan** [comment]
Did you see a `service create` event in the beginning?

**Comment by vce-xx** [comment]
Yes

``
2018-05-27T19:01:08.115101362Z container exec_create: /bin/sh -c check.sh 
492a7f004d7725e67834b47bc72fc245cfd99dda2e421f08dd28f2d3d60e29a4 (com.docker.stack.namespace=my-proxy, 
com.docker.swarm.node.id=9i8857es9ngyvyb0q7zeq0ixb, com.docker.swarm.service.id=6wlj3hjfliyhhso7ep76l2ybn, 
com.docker.swarm.service.name=my-proxy_my-proxy, com.docker.swarm.task=, com.docker.swarm.task.id=1issch43i7i4sqdan8tqxygd7, 
com.docker.swarm.task.name=my-proxy_my-proxy.1.1issch43i7i4sqdan8tqxygd7, 
execID=eecd79e3db6471e3871a1150a090a01a3f61eee6f82316a990167c91f13ead42, image=dockerflow/
docker-flow-proxy:18.05.23-50@sha256:7ffa39045d342adffb1aa18671f871681b08d1cfdf4aa54c9cbc9562ce5141c1, 
name=my-proxy_my-proxy.1.1issch43i7i4sqdan8tqxygd7)
2018-05-27T19:01:08.115330616Z container exec_start: /bin/sh -c check.sh 
492a7f004d7725e67834b47bc72fc245cfd99dda2e421f08dd28f2d3d60e29a4 (com.docker.stack.namespace=my-proxy, 
com.docker.swarm.node.id=9i8857es9ngyvyb0q7zeq0ixb, com.docker.swarm.service.id=6wlj3hjfliyhhso7ep76l2ybn, 
com.docker.swarm.service.name=my-proxy_my-proxy, com.docker.swarm.task=, com.docker.swarm.task.id=1issch43i7i4sqdan8tqxygd7, 
com.docker.swarm.task.name=my-proxy_my-proxy.1.1issch43i7i4sqdan8tqxygd7, 
execID=eecd79e3db6471e3871a1150a090a01a3f61eee6f82316a990167c91f13ead42, image=dockerflow/
docker-flow-proxy:18.05.23-50@sha256:7ffa39045d342adffb1aa18671f871681b08d1cfdf4aa54c9cbc9562ce5141c1, 
name=my-proxy_my-proxy.1.1issch43i7i4sqdan8tqxygd7)
2018-05-27T19:01:08.164482407Z container exec_die 492a7f004d7725e67834b47bc72fc245cfd99dda2e421f08dd28f2d3d60e29a4 (
com.docker.stack.namespace=my-proxy, com.docker.swarm.node.id=9i8857es9ngyvyb0q7zeq0ixb, 
com.docker.swarm.service.id=6wlj3hjfliyhhso7ep76l2ybn, com.docker.swarm.service.name=my-proxy_my-proxy, com.docker.swarm.task=, 
com.docker.swarm.task.id=1issch43i7i4sqdan8tqxygd7, com.docker.swarm.task.name=my-proxy_my-proxy.1.1issch43i7i4sqdan8tqxygd7, 
execID=eecd79e3db6471e3871a1150a090a01a3f61eee6f82316a990167c91f13ead42, exitCode=0, image=dockerflow/
docker-flow-proxy:18.05.23-50@sha256:7ffa39045d342adffb1aa18671f871681b08d1cfdf4aa54c9cbc9562ce5141c1, 
name=my-proxy_my-proxy.1.1issch43i7i4sqdan8tqxygd7)
```

**Comment by vce-xx** [comment]
What puzzles me even more now is that `docker events --filter type=service` didn't report anything when executing :
```
docker service create --name test nginx
docker service update --replicas=3 test
docker service rm test
```

**Comment by thomasjpfan** [comment]
The `exec_create`, `exec_start`, `exec_die` cycle runs because of the healthcheck. The container/service does not shutdown since the healthcheck returns a status code of 0.

I'm looking for a service event, something similar to this:

```
service create jikz9ct23mf9pqnedu4vm02oe (name=proxy)
service update jikz9ct23mf9pqnedu4vm02oe (name=proxy)
```

Can you have two windows open, one with `docker events --filter type=service` and `docker events --filter type=container` on your nginx service and copy the results here?

**Comment by vce-xx** [comment]
The healthcheck. Nice !
So I disabled it for clarity of the output :
```
  swarm-listener:
    image: dockerflow/docker-flow-swarm-listener:18.05.27-15
    healthcheck:
      disable: true
```
So running side by side the two commands then running `docker service create --name test --label "com.df.notify=true" --label "com.df.distribute=true" --label "com.df.servicePath=/hello" --label "com.df.port=4443" nginx` and `docker service rm test`
With `docker events` no output (void).
With `docker events --filter type=service` no output (void).

**Comment by thomasjpfan** [comment]
That is really strange. I think I need to directly test this on AWS with your configuration. Can you detail how you are starting up your AWS instance?

**Comment by vce-xx** [comment]
I am using [Docker for AWS](https://docs.docker.com/docker-for-aws/#quickstart) stable channel.

**Comment by thomasjpfan** [comment]
@vce-xx What region are you in?

**Comment by thomasjpfan** [comment]
@vce-xx I just launched us-east AWS instances with 3 managers (`Docker version 18.03.0-ce`), and used the following stack files:

### proxy.yml

```yaml
version: '3.1'

services:

  proxy:
    image: dockerflow/docker-flow-proxy:18.05.08-46
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - TIMEOUT_SERVER=60
      - CONNECTION_MODE=http-server-close
    deploy:
      replicas: 2

  swarm-listener:
    image: dockerflow/docker-flow-swarm-listener:18.05.27-15
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  proxy:
    external: true
```

### nginx.yml

```yaml
version: '3.1'
services:

  ui:
    image: nginx:1.13.12-alpine
    ports:
      - "3000:80"
    networks:
      - proxy
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 120s
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.port=80

networks:
  proxy:
    external: true
```

And ran:

```bash
docker network create -d overlay proxy
docker stack deploy -c proxy.yml proxy
docker stack deploy -c nginx.yml nginx
docker stack rm nginx
docker stack deploy -c nginx.yml nginx
docker stack rm nginx
```

Everything seemed to be working correctly, here is a screenshot of my session:

<img width="2027" alt="screen shot 2018-05-27 at 6 52 44 pm" src="https://user-images.githubusercontent.com/5402633/40591461-d49f270c-61df-11e8-82c4-1047ef34b062.png">

I really want to reproduce this issue. It seems like in your case, the events are not firing, which means DFSL will not be able to see the events as well.
